# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cidrgrep < Formula
  desc "like grep but for IP/CIDR matching"
  homepage "https://github.com/dotnetmentor/cidrgrep"
  version "0.1.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dotnetmentor/cidrgrep/releases/download/v0.1.0/cidrgrep_v0.1.0_darwin_arm64.zip"
      sha256 "80f5fff794366b9bb348cf639f7dec1c9230aa44283e977b62a6f3d5884a027d"

      def install
        bin.install 'cidrgrep'
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'bash')
        (bash_completion/'cidrgrep').write output
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'zsh')
        (zsh_completion/'_cidrgrep').write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dotnetmentor/cidrgrep/releases/download/v0.1.0/cidrgrep_v0.1.0_darwin_amd64.zip"
      sha256 "00ea240d0d7333eee41156f789a7d1e4562f94845739447c83d55dbc3301dc73"

      def install
        bin.install 'cidrgrep'
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'bash')
        (bash_completion/'cidrgrep').write output
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'zsh')
        (zsh_completion/'_cidrgrep').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dotnetmentor/cidrgrep/releases/download/v0.1.0/cidrgrep_v0.1.0_linux_amd64.tar.gz"
      sha256 "37d38ac0061392df0f726c44bcf7ccee352c743bf3aa861fe799747995df8226"

      def install
        bin.install 'cidrgrep'
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'bash')
        (bash_completion/'cidrgrep').write output
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'zsh')
        (zsh_completion/'_cidrgrep').write output
      end
    end
  end
end
