# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cidrgrep < Formula
  desc "like grep but for IP/CIDR matching"
  homepage "https://github.com/dotnetmentor/cidrgrep"
  version "0.1.1"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dotnetmentor/cidrgrep/releases/download/v0.1.1/cidrgrep_v0.1.1_darwin_arm64.zip"
      sha256 "0423da7b4ef29f4997f485fe2acda0043e40f046aefa9c22ce4545552e4624ec"

      def install
        bin.install 'cidrgrep'
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'bash')
        (bash_completion/'cidrgrep').write output
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'zsh')
        (zsh_completion/'_cidrgrep').write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dotnetmentor/cidrgrep/releases/download/v0.1.1/cidrgrep_v0.1.1_darwin_amd64.zip"
      sha256 "6e135078ff3893922dca002984f9a25f43ecebcdf3556fa754ad4091a93f569c"

      def install
        bin.install 'cidrgrep'
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'bash')
        (bash_completion/'cidrgrep').write output
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'zsh')
        (zsh_completion/'_cidrgrep').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dotnetmentor/cidrgrep/releases/download/v0.1.1/cidrgrep_v0.1.1_linux_amd64.tar.gz"
      sha256 "73787f86759ee9b6aa48a8892a3f8e4f3e7fa16dc9ad9a7b1132800a9aa0f9ed"

      def install
        bin.install 'cidrgrep'
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'bash')
        (bash_completion/'cidrgrep').write output
        output = Utils.safe_popen_read("#{bin}/cidrgrep", 'completion', 'zsh')
        (zsh_completion/'_cidrgrep').write output
      end
    end
  end
end
