# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuzzytest < Formula
  desc "fuzzy tool"
  homepage "https://github.com/dotnetmentor/fuzzytest"
  version "0.1.0"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dotnetmentor/fuzzytest/releases/download/v0.1.0/fuzzytest_v0.1.0_darwin_arm64.zip"
      sha256 "6e53611bbf1cf16c30c8f8b76c4aee2b72dc4b42523ebad3b8855f96cd77ca4b"

      def install
        bin.install 'fuzzytest'
        output = Utils.safe_popen_read("#{bin}/fuzzytest", 'completion', 'bash')
        (bash_completion/'fuzzytest').write output
        output = Utils.safe_popen_read("#{bin}/fuzzytest", 'completion', 'zsh')
        (zsh_completion/'_fuzzytest').write output
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dotnetmentor/fuzzytest/releases/download/v0.1.0/fuzzytest_v0.1.0_darwin_amd64.zip"
      sha256 "0cf2100ca15cd55543fab68dc3a1fa707e3b6300d38936a30325600bade6a1d1"

      def install
        bin.install 'fuzzytest'
        output = Utils.safe_popen_read("#{bin}/fuzzytest", 'completion', 'bash')
        (bash_completion/'fuzzytest').write output
        output = Utils.safe_popen_read("#{bin}/fuzzytest", 'completion', 'zsh')
        (zsh_completion/'_fuzzytest').write output
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dotnetmentor/fuzzytest/releases/download/v0.1.0/fuzzytest_v0.1.0_linux_amd64.tar.gz"
      sha256 "630cc7cfce1330c034bfc9f3477c0f78a56746ffb56e425275f8ef1819ddd27d"

      def install
        bin.install 'fuzzytest'
        output = Utils.safe_popen_read("#{bin}/fuzzytest", 'completion', 'bash')
        (bash_completion/'fuzzytest').write output
        output = Utils.safe_popen_read("#{bin}/fuzzytest", 'completion', 'zsh')
        (zsh_completion/'_fuzzytest').write output
      end
    end
  end
end
